version: '3.8'

services:
  blog-api:
    build: .
    container_name: blog-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/schema/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
